#server:
#  port: 8081
#
#spring:
#  cloud:
#    gateway:
#      server:
#        webmvc:
#          routes:
#            - id: book-service
#              uri: http://localhost:8080
#              predicates:
#                - Path=/api/books/**
#
#server:
#  port: 8081
#
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: book-service
#          uri: http://localhost:8080
#          predicates:
#            - Path=/api/books/**

server:
  port: 8081

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: book-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/books/**
              filters:
                - name: CustomFilter
                  args:
                    afterMessage: "Request telah selesai untuk path "
                    beforeMessage: "Request masuk ke book-service untuk path "

